apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "microservice-stack.fullname" . }}-prometheus
  labels:
    app: {{ template "microservice-stack.name" . }}-prometheus
    chart: {{ template "microservice-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "microservice-stack.name" . }}-prometheus
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "microservice-stack.name" . }}-prometheus
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.prometheus.name }}
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          command: ["/bin/prometheus"]
          args: ["--config.file", "/etc/prometheus/prometheus.yml",
                "--storage.tsdb.path", "/prometheus",
                "--web.console.libraries", "/usr/share/prometheus/console_libraries",
                "--web.console.templates", "/usr/share/prometheus/consoles" ]
          ports:
            - name: http
              containerPort: {{ .Values.prometheus.service.port }}
              protocol: TCP
          volumeMounts:
          - name: prometheus
            mountPath: "/etc/prometheus/"
      volumes:
        - name: prometheus
          configMap:
            name: {{ template "microservice-stack.fullname" . }}-prometheus
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
